version: '3.1'

services:
  nginx:
    image: nginx:1.21-alpine
    restart: always
    container_name: bm-nginx
    working_dir: /home/app
    volumes:
      - ./app:/home/app:cached
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:cached
      - ./nginx/sites-enabled/app.conf:/etc/nginx/conf.d/default.conf:cached
    ports:
      - "127.0.0.1:9000:80"
    networks:
      - bm

  phpfpm:
    build: phpfpm
    restart: always
    container_name: bm-phpfpm
    working_dir: /home/app
    volumes:
        - ./app:/home/app:cached
    networks:
      - bm

  mysql:
    image: mysql:5.7
    restart: always
    container_name: bm-mysql
    ports:
      - "127.0.0.1:3307:3306"
    volumes:
      - ./.mysql-data:/var/lib/mysql:delegated
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - bm

networks:
  bm:
